# executable files for this directory
OBJECTS = length_of_longest_substring.exe anagrams.exe length_of_last_word.exe\
	  reverse_string.exe search_for_a_range.exe removePuncts.exe\
	  longest_common_profix.exe

include ../makefile.commom
