# executable files for this directory
OBJECTS = length_of_longest_substring.exe anagrams.exe length_of_last_word.exe\
	  reverse_string.exe search_for_a_range.exe removePuncts.exe\
	  longest_common_profix.exe num_of_distinct_subsequence.exe\
	  reverseWords.exe next_permutation.exe atoi.exe\
	  add_binary.exe simplify_path.exe compare_version_numbers.exe

include ../makefile.commom
