# executable files for this directory
OBJECTS = longest_continus_subarray_sum_up_to_zero.exe minimal_number_of_insertions_to_create_palindrome.exe\
	  first_non_repeating_char.exe quadtree_intersections.exe\
	  find_all_factors.exe

include ../../makefile.commom
