# executable files for this directory
OBJECTS = combinations.exe palindrome_partitioning.exe permutation_sequence.exe \
	  word_break_2.exe combinations_.exe subset_ii.exe

include ../makefile.commom
