# executable files for this directory
OBJECTS = triangle.exe palindrome_partitioning_II.exe make_changes.exe make_changes_ii.exe\
	  longest_common_substring.exe backpack_ii.exe decode_ways.exe\


include ../makefile.commom
