# executable files for this directory
OBJECTS = triangle.exe palindrome_partitioning_II.exe make_changes.exe make_changes_ii.exe\
	  maximum_subarray.exe distinct_subsequences.exe

include ../makefile.commom
